---
title: "Classwork"
author: "Darya Nemirich"
date: '10 May 2019'
output: pdf_document
---

```{r}
load("D:/Bioinformatics and System Biology/2nd term/R/R_classwork/Case/CHIS2009_reduced_2.Rdata")
```
```{r}
head(adult)
str(adult)

```
```{r}
adult$RBMI <- as.factor(adult$RBMI)

str(adult)
```


```{r}
library(ggplot2)
```


```{r}
plot1 <- ggplot(adult, aes(x = SRAGE_P, fill = RBMI)) + 
  geom_histogram(binwidth = 1) + 
  xlab("age")

plot1
```
```{r}
library(dplyr)
```

```{r}
adult_tidy <- adult %>% 
  filter(SRAGE_P < 85) %>% 
  filter(BMI_P < 52 & BMI_P >= 16) %>% 
  mutate(RACEHPR2 = factor(RACEHPR2,
                           levels = c(1, 4, 5, 6),
                           labels = c("Latino", "Asian", "African American", "White"))) %>% 
  mutate(RBMI = factor(RBMI,
                       levels = c(1, 2, 3, 4),
                       labels = c("Under", "Normal", "Over", "Obese")))

  
str(adult_tidy)

```

```{r}
plot2 <- ggplot(adult_tidy, aes(x = SRAGE_P, fill = RBMI)) + 
  geom_histogram(binwidth = 1, position = "stack") + 
  xlab("age") +
  facet_grid(RBMI ~ .) +
  scale_fill_brewer("BMI group", palette = "Reds") +
  theme_classic() +
  theme(strip.text.y = element_blank())

plot2
```

```{r}
plot3 <- ggplot(adult_tidy, aes(x = SRAGE_P, fill = RBMI)) + 
  geom_histogram(position = "fill", bins = 66) + 
  xlab("age") +
  ylab("percentage") +
  facet_grid(RBMI ~ .) +
  scale_fill_brewer("BMI group", palette = "Reds") +
  theme_classic() +
  theme(strip.text.y = element_blank())

plot3
```
```{r}
library(reshape2)
```

```{r}
frequencies_table <- dcast(adult_tidy, SRAGE_P ~ RBMI, length)
head(frequencies_table)
```
```{r}
melted_freq <- reshape2::melt(frequencies_table, id.vars="SRAGE_P", measured.vars=c("Under", "Normal", "Over", "Obese"))

head(melted_freq)
```
```{r}
plot4 <- ggplot(melted_freq, aes(x = SRAGE_P, y = value, fill = variable)) + 
  geom_col() + 
  xlab('age') +
  ylab('count') +
  facet_grid(. ~ variable) +
  scale_fill_brewer("BMI group", palette = "Reds") +
  theme_classic() +
  theme(strip.text.y = element_blank())

plot4
```


